sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env:
      - COLUMNS=80
      - TOX_ENV=py36
  - python: 3.6
    env:
      - COLUMNS=80
      - TOX_ENV=py36
  - python: 3.7
    env:
      - COLUMNS=80
      - TOX_ENV=py36
    sudo: required
    dist: xenial
install:
- pip install tox
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
